package com.nf147.distrbution.dao;

import com.nf147.distrbution.entity.Sscar;
import java.util.List;

public interface SscarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscar
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscar
     *
     * @mbg.generated
     */
    int insert(Sscar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscar
     *
     * @mbg.generated
     */
    Sscar selectByPrimaryKey(String carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscar
     *
     * @mbg.generated
     */
    List<Sscar> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscar
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sscar record);
}