package com.nf147.distrbution.dao;

import com.nf147.distrbution.entity.Sscity;
import java.util.List;

public interface SscityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscity
     *
     * @mbg.generated
     */
    int insert(Sscity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscity
     *
     * @mbg.generated
     */
    Sscity selectByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscity
     *
     * @mbg.generated
     */
    List<Sscity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sscity record);
}