package com.nf147.distrbution.dao;

import com.nf147.distrbution.entity.Sscustomer;
import java.util.List;

public interface SscustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscustomer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscustomer
     *
     * @mbg.generated
     */
    int insert(Sscustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscustomer
     *
     * @mbg.generated
     */
    Sscustomer selectByPrimaryKey(String cuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscustomer
     *
     * @mbg.generated
     */
    List<Sscustomer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sscustomer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sscustomer record);
}