package com.nf147.distrbution.dao;

import com.nf147.distrbution.entity.Ssdeliveryreceipt;
import java.util.List;

public interface SsdeliveryreceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryreceipt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deliveryReceipt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryreceipt
     *
     * @mbg.generated
     */
    int insert(Ssdeliveryreceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryreceipt
     *
     * @mbg.generated
     */
    Ssdeliveryreceipt selectByPrimaryKey(String deliveryReceipt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryreceipt
     *
     * @mbg.generated
     */
    List<Ssdeliveryreceipt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryreceipt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ssdeliveryreceipt record);
}