package com.nf147.distrbution.dao;

import com.nf147.distrbution.entity.Ssdeliveryrange;
import java.util.List;

public interface SsdeliveryrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryrange
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryrange
     *
     * @mbg.generated
     */
    int insert(Ssdeliveryrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryrange
     *
     * @mbg.generated
     */
    Ssdeliveryrange selectByPrimaryKey(String rangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryrange
     *
     * @mbg.generated
     */
    List<Ssdeliveryrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssdeliveryrange
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ssdeliveryrange record);
}