package com.nf147.distrbution.dao;

import com.nf147.distrbution.entity.Ssmanager;
import java.util.List;

public interface SsmanagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssmanager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String mgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssmanager
     *
     * @mbg.generated
     */
    int insert(Ssmanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssmanager
     *
     * @mbg.generated
     */
    Ssmanager selectByPrimaryKey(String mgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssmanager
     *
     * @mbg.generated
     */
    List<Ssmanager> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssmanager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ssmanager record);
}