package com.nf147.distrbution.dao;

import com.nf147.distrbution.entity.Ssprivance;
import java.util.List;

public interface SsprivanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssprivance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssprivance
     *
     * @mbg.generated
     */
    int insert(Ssprivance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssprivance
     *
     * @mbg.generated
     */
    Ssprivance selectByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssprivance
     *
     * @mbg.generated
     */
    List<Ssprivance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ssprivance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ssprivance record);
}