package com.nf147.distrbution.entity;

public class Ssassociation1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssassociation1.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssassociation1.delivery_Receiptid
     *
     * @mbg.generated
     */
    private String deliveryReceiptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssassociation1.order_id
     *
     * @return the value of ssassociation1.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssassociation1.order_id
     *
     * @param orderId the value for ssassociation1.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssassociation1.delivery_Receiptid
     *
     * @return the value of ssassociation1.delivery_Receiptid
     *
     * @mbg.generated
     */
    public String getDeliveryReceiptid() {
        return deliveryReceiptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssassociation1.delivery_Receiptid
     *
     * @param deliveryReceiptid the value for ssassociation1.delivery_Receiptid
     *
     * @mbg.generated
     */
    public void setDeliveryReceiptid(String deliveryReceiptid) {
        this.deliveryReceiptid = deliveryReceiptid == null ? null : deliveryReceiptid.trim();
    }
}