package com.nf147.distrbution.entity;

import java.util.Date;

public class Sscar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscar.car_id
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscar.rote_id
     *
     * @mbg.generated
     */
    private String roteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscar.car_type
     *
     * @mbg.generated
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscar.car_orgin
     *
     * @mbg.generated
     */
    private String carOrgin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscar.car_pro_date
     *
     * @mbg.generated
     */
    private Date carProDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscar.car_but_date
     *
     * @mbg.generated
     */
    private Date carButDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscar.car_capacity
     *
     * @mbg.generated
     */
    private Integer carCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscar.car_state
     *
     * @mbg.generated
     */
    private Boolean carState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscar.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscar.car_id
     *
     * @return the value of sscar.car_id
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscar.car_id
     *
     * @param carId the value for sscar.car_id
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscar.rote_id
     *
     * @return the value of sscar.rote_id
     *
     * @mbg.generated
     */
    public String getRoteId() {
        return roteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscar.rote_id
     *
     * @param roteId the value for sscar.rote_id
     *
     * @mbg.generated
     */
    public void setRoteId(String roteId) {
        this.roteId = roteId == null ? null : roteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscar.car_type
     *
     * @return the value of sscar.car_type
     *
     * @mbg.generated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscar.car_type
     *
     * @param carType the value for sscar.car_type
     *
     * @mbg.generated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscar.car_orgin
     *
     * @return the value of sscar.car_orgin
     *
     * @mbg.generated
     */
    public String getCarOrgin() {
        return carOrgin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscar.car_orgin
     *
     * @param carOrgin the value for sscar.car_orgin
     *
     * @mbg.generated
     */
    public void setCarOrgin(String carOrgin) {
        this.carOrgin = carOrgin == null ? null : carOrgin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscar.car_pro_date
     *
     * @return the value of sscar.car_pro_date
     *
     * @mbg.generated
     */
    public Date getCarProDate() {
        return carProDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscar.car_pro_date
     *
     * @param carProDate the value for sscar.car_pro_date
     *
     * @mbg.generated
     */
    public void setCarProDate(Date carProDate) {
        this.carProDate = carProDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscar.car_but_date
     *
     * @return the value of sscar.car_but_date
     *
     * @mbg.generated
     */
    public Date getCarButDate() {
        return carButDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscar.car_but_date
     *
     * @param carButDate the value for sscar.car_but_date
     *
     * @mbg.generated
     */
    public void setCarButDate(Date carButDate) {
        this.carButDate = carButDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscar.car_capacity
     *
     * @return the value of sscar.car_capacity
     *
     * @mbg.generated
     */
    public Integer getCarCapacity() {
        return carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscar.car_capacity
     *
     * @param carCapacity the value for sscar.car_capacity
     *
     * @mbg.generated
     */
    public void setCarCapacity(Integer carCapacity) {
        this.carCapacity = carCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscar.car_state
     *
     * @return the value of sscar.car_state
     *
     * @mbg.generated
     */
    public Boolean getCarState() {
        return carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscar.car_state
     *
     * @param carState the value for sscar.car_state
     *
     * @mbg.generated
     */
    public void setCarState(Boolean carState) {
        this.carState = carState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscar.comment
     *
     * @return the value of sscar.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscar.comment
     *
     * @param comment the value for sscar.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}