package com.nf147.distrbution.entity;

public class Sscityarea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscityarea.area_id
     *
     * @mbg.generated
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscityarea.city_id
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscityarea.range_id
     *
     * @mbg.generated
     */
    private String rangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscityarea.area_name
     *
     * @mbg.generated
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sscityarea.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscityarea.area_id
     *
     * @return the value of sscityarea.area_id
     *
     * @mbg.generated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscityarea.area_id
     *
     * @param areaId the value for sscityarea.area_id
     *
     * @mbg.generated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscityarea.city_id
     *
     * @return the value of sscityarea.city_id
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscityarea.city_id
     *
     * @param cityId the value for sscityarea.city_id
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscityarea.range_id
     *
     * @return the value of sscityarea.range_id
     *
     * @mbg.generated
     */
    public String getRangeId() {
        return rangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscityarea.range_id
     *
     * @param rangeId the value for sscityarea.range_id
     *
     * @mbg.generated
     */
    public void setRangeId(String rangeId) {
        this.rangeId = rangeId == null ? null : rangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscityarea.area_name
     *
     * @return the value of sscityarea.area_name
     *
     * @mbg.generated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscityarea.area_name
     *
     * @param areaName the value for sscityarea.area_name
     *
     * @mbg.generated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sscityarea.city_name
     *
     * @return the value of sscityarea.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sscityarea.city_name
     *
     * @param cityName the value for sscityarea.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }
}