package com.nf147.distrbution.entity;

public class Ssdeliveryplace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryplace.dep_id
     *
     * @mbg.generated
     */
    private String depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryplace.mg_id
     *
     * @mbg.generated
     */
    private String mgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryplace.dep_name
     *
     * @mbg.generated
     */
    private String depName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryplace.province_name
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryplace.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryplace.mg_name
     *
     * @mbg.generated
     */
    private String mgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryplace.dep_tel
     *
     * @mbg.generated
     */
    private String depTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryplace.dep_addr
     *
     * @mbg.generated
     */
    private String depAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryplace.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryplace.dep_id
     *
     * @return the value of ssdeliveryplace.dep_id
     *
     * @mbg.generated
     */
    public String getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryplace.dep_id
     *
     * @param depId the value for ssdeliveryplace.dep_id
     *
     * @mbg.generated
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryplace.mg_id
     *
     * @return the value of ssdeliveryplace.mg_id
     *
     * @mbg.generated
     */
    public String getMgId() {
        return mgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryplace.mg_id
     *
     * @param mgId the value for ssdeliveryplace.mg_id
     *
     * @mbg.generated
     */
    public void setMgId(String mgId) {
        this.mgId = mgId == null ? null : mgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryplace.dep_name
     *
     * @return the value of ssdeliveryplace.dep_name
     *
     * @mbg.generated
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryplace.dep_name
     *
     * @param depName the value for ssdeliveryplace.dep_name
     *
     * @mbg.generated
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryplace.province_name
     *
     * @return the value of ssdeliveryplace.province_name
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryplace.province_name
     *
     * @param provinceName the value for ssdeliveryplace.province_name
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryplace.city_name
     *
     * @return the value of ssdeliveryplace.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryplace.city_name
     *
     * @param cityName the value for ssdeliveryplace.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryplace.mg_name
     *
     * @return the value of ssdeliveryplace.mg_name
     *
     * @mbg.generated
     */
    public String getMgName() {
        return mgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryplace.mg_name
     *
     * @param mgName the value for ssdeliveryplace.mg_name
     *
     * @mbg.generated
     */
    public void setMgName(String mgName) {
        this.mgName = mgName == null ? null : mgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryplace.dep_tel
     *
     * @return the value of ssdeliveryplace.dep_tel
     *
     * @mbg.generated
     */
    public String getDepTel() {
        return depTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryplace.dep_tel
     *
     * @param depTel the value for ssdeliveryplace.dep_tel
     *
     * @mbg.generated
     */
    public void setDepTel(String depTel) {
        this.depTel = depTel == null ? null : depTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryplace.dep_addr
     *
     * @return the value of ssdeliveryplace.dep_addr
     *
     * @mbg.generated
     */
    public String getDepAddr() {
        return depAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryplace.dep_addr
     *
     * @param depAddr the value for ssdeliveryplace.dep_addr
     *
     * @mbg.generated
     */
    public void setDepAddr(String depAddr) {
        this.depAddr = depAddr == null ? null : depAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryplace.comment
     *
     * @return the value of ssdeliveryplace.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryplace.comment
     *
     * @param comment the value for ssdeliveryplace.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}