package com.nf147.distrbution.entity;

public class Ssdeliveryreceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryreceipt.delivery_receipt
     *
     * @mbg.generated
     */
    private String deliveryReceipt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryreceipt.stary_city
     *
     * @mbg.generated
     */
    private String staryCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryreceipt.end_city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryreceipt.mid_city
     *
     * @mbg.generated
     */
    private String midCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryreceipt.make_dtae
     *
     * @mbg.generated
     */
    private String makeDtae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryreceipt.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssdeliveryreceipt.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryreceipt.delivery_receipt
     *
     * @return the value of ssdeliveryreceipt.delivery_receipt
     *
     * @mbg.generated
     */
    public String getDeliveryReceipt() {
        return deliveryReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryreceipt.delivery_receipt
     *
     * @param deliveryReceipt the value for ssdeliveryreceipt.delivery_receipt
     *
     * @mbg.generated
     */
    public void setDeliveryReceipt(String deliveryReceipt) {
        this.deliveryReceipt = deliveryReceipt == null ? null : deliveryReceipt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryreceipt.stary_city
     *
     * @return the value of ssdeliveryreceipt.stary_city
     *
     * @mbg.generated
     */
    public String getStaryCity() {
        return staryCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryreceipt.stary_city
     *
     * @param staryCity the value for ssdeliveryreceipt.stary_city
     *
     * @mbg.generated
     */
    public void setStaryCity(String staryCity) {
        this.staryCity = staryCity == null ? null : staryCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryreceipt.end_city
     *
     * @return the value of ssdeliveryreceipt.end_city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryreceipt.end_city
     *
     * @param endCity the value for ssdeliveryreceipt.end_city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryreceipt.mid_city
     *
     * @return the value of ssdeliveryreceipt.mid_city
     *
     * @mbg.generated
     */
    public String getMidCity() {
        return midCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryreceipt.mid_city
     *
     * @param midCity the value for ssdeliveryreceipt.mid_city
     *
     * @mbg.generated
     */
    public void setMidCity(String midCity) {
        this.midCity = midCity == null ? null : midCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryreceipt.make_dtae
     *
     * @return the value of ssdeliveryreceipt.make_dtae
     *
     * @mbg.generated
     */
    public String getMakeDtae() {
        return makeDtae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryreceipt.make_dtae
     *
     * @param makeDtae the value for ssdeliveryreceipt.make_dtae
     *
     * @mbg.generated
     */
    public void setMakeDtae(String makeDtae) {
        this.makeDtae = makeDtae == null ? null : makeDtae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryreceipt.state
     *
     * @return the value of ssdeliveryreceipt.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryreceipt.state
     *
     * @param state the value for ssdeliveryreceipt.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssdeliveryreceipt.comment
     *
     * @return the value of ssdeliveryreceipt.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssdeliveryreceipt.comment
     *
     * @param comment the value for ssdeliveryreceipt.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}