package com.nf147.distrbution.entity;

public class Ssmanager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssmanager.mg_id
     *
     * @mbg.generated
     */
    private String mgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssmanager.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssmanager.manager_name
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssmanager.manager_psd
     *
     * @mbg.generated
     */
    private String managerPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssmanager.manager_sex
     *
     * @mbg.generated
     */
    private String managerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssmanager.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssmanager.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssmanager.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssmanager.mg_id
     *
     * @return the value of ssmanager.mg_id
     *
     * @mbg.generated
     */
    public String getMgId() {
        return mgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssmanager.mg_id
     *
     * @param mgId the value for ssmanager.mg_id
     *
     * @mbg.generated
     */
    public void setMgId(String mgId) {
        this.mgId = mgId == null ? null : mgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssmanager.role_id
     *
     * @return the value of ssmanager.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssmanager.role_id
     *
     * @param roleId the value for ssmanager.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssmanager.manager_name
     *
     * @return the value of ssmanager.manager_name
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssmanager.manager_name
     *
     * @param managerName the value for ssmanager.manager_name
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssmanager.manager_psd
     *
     * @return the value of ssmanager.manager_psd
     *
     * @mbg.generated
     */
    public String getManagerPsd() {
        return managerPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssmanager.manager_psd
     *
     * @param managerPsd the value for ssmanager.manager_psd
     *
     * @mbg.generated
     */
    public void setManagerPsd(String managerPsd) {
        this.managerPsd = managerPsd == null ? null : managerPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssmanager.manager_sex
     *
     * @return the value of ssmanager.manager_sex
     *
     * @mbg.generated
     */
    public String getManagerSex() {
        return managerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssmanager.manager_sex
     *
     * @param managerSex the value for ssmanager.manager_sex
     *
     * @mbg.generated
     */
    public void setManagerSex(String managerSex) {
        this.managerSex = managerSex == null ? null : managerSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssmanager.tel
     *
     * @return the value of ssmanager.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssmanager.tel
     *
     * @param tel the value for ssmanager.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssmanager.address
     *
     * @return the value of ssmanager.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssmanager.address
     *
     * @param address the value for ssmanager.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssmanager.comment
     *
     * @return the value of ssmanager.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssmanager.comment
     *
     * @param comment the value for ssmanager.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}