package com.nf147.distrbution.entity;

import java.math.BigDecimal;

public class Ssorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.car_id
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.cu_id
     *
     * @mbg.generated
     */
    private String cuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.post_pname
     *
     * @mbg.generated
     */
    private String postPname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.post_ptel
     *
     * @mbg.generated
     */
    private String postPtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.post_paddr
     *
     * @mbg.generated
     */
    private String postPaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.get_pname
     *
     * @mbg.generated
     */
    private String getPname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.gte_ptel
     *
     * @mbg.generated
     */
    private String gtePtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.get_paddr
     *
     * @mbg.generated
     */
    private String getPaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.goods_Weight
     *
     * @mbg.generated
     */
    private Integer goodsWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.order_state
     *
     * @mbg.generated
     */
    private String orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.transpot_price
     *
     * @mbg.generated
     */
    private BigDecimal transpotPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.delivery_price
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.total_price
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssorder.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.order_id
     *
     * @return the value of ssorder.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.order_id
     *
     * @param orderId the value for ssorder.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.car_id
     *
     * @return the value of ssorder.car_id
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.car_id
     *
     * @param carId the value for ssorder.car_id
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.cu_id
     *
     * @return the value of ssorder.cu_id
     *
     * @mbg.generated
     */
    public String getCuId() {
        return cuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.cu_id
     *
     * @param cuId the value for ssorder.cu_id
     *
     * @mbg.generated
     */
    public void setCuId(String cuId) {
        this.cuId = cuId == null ? null : cuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.post_pname
     *
     * @return the value of ssorder.post_pname
     *
     * @mbg.generated
     */
    public String getPostPname() {
        return postPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.post_pname
     *
     * @param postPname the value for ssorder.post_pname
     *
     * @mbg.generated
     */
    public void setPostPname(String postPname) {
        this.postPname = postPname == null ? null : postPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.post_ptel
     *
     * @return the value of ssorder.post_ptel
     *
     * @mbg.generated
     */
    public String getPostPtel() {
        return postPtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.post_ptel
     *
     * @param postPtel the value for ssorder.post_ptel
     *
     * @mbg.generated
     */
    public void setPostPtel(String postPtel) {
        this.postPtel = postPtel == null ? null : postPtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.post_paddr
     *
     * @return the value of ssorder.post_paddr
     *
     * @mbg.generated
     */
    public String getPostPaddr() {
        return postPaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.post_paddr
     *
     * @param postPaddr the value for ssorder.post_paddr
     *
     * @mbg.generated
     */
    public void setPostPaddr(String postPaddr) {
        this.postPaddr = postPaddr == null ? null : postPaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.get_pname
     *
     * @return the value of ssorder.get_pname
     *
     * @mbg.generated
     */
    public String getGetPname() {
        return getPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.get_pname
     *
     * @param getPname the value for ssorder.get_pname
     *
     * @mbg.generated
     */
    public void setGetPname(String getPname) {
        this.getPname = getPname == null ? null : getPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.gte_ptel
     *
     * @return the value of ssorder.gte_ptel
     *
     * @mbg.generated
     */
    public String getGtePtel() {
        return gtePtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.gte_ptel
     *
     * @param gtePtel the value for ssorder.gte_ptel
     *
     * @mbg.generated
     */
    public void setGtePtel(String gtePtel) {
        this.gtePtel = gtePtel == null ? null : gtePtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.get_paddr
     *
     * @return the value of ssorder.get_paddr
     *
     * @mbg.generated
     */
    public String getGetPaddr() {
        return getPaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.get_paddr
     *
     * @param getPaddr the value for ssorder.get_paddr
     *
     * @mbg.generated
     */
    public void setGetPaddr(String getPaddr) {
        this.getPaddr = getPaddr == null ? null : getPaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.goods_name
     *
     * @return the value of ssorder.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.goods_name
     *
     * @param goodsName the value for ssorder.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.goods_Weight
     *
     * @return the value of ssorder.goods_Weight
     *
     * @mbg.generated
     */
    public Integer getGoodsWeight() {
        return goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.goods_Weight
     *
     * @param goodsWeight the value for ssorder.goods_Weight
     *
     * @mbg.generated
     */
    public void setGoodsWeight(Integer goodsWeight) {
        this.goodsWeight = goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.order_type
     *
     * @return the value of ssorder.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.order_type
     *
     * @param orderType the value for ssorder.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.order_state
     *
     * @return the value of ssorder.order_state
     *
     * @mbg.generated
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.order_state
     *
     * @param orderState the value for ssorder.order_state
     *
     * @mbg.generated
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState == null ? null : orderState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.transpot_price
     *
     * @return the value of ssorder.transpot_price
     *
     * @mbg.generated
     */
    public BigDecimal getTranspotPrice() {
        return transpotPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.transpot_price
     *
     * @param transpotPrice the value for ssorder.transpot_price
     *
     * @mbg.generated
     */
    public void setTranspotPrice(BigDecimal transpotPrice) {
        this.transpotPrice = transpotPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.delivery_price
     *
     * @return the value of ssorder.delivery_price
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.delivery_price
     *
     * @param deliveryPrice the value for ssorder.delivery_price
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.total_price
     *
     * @return the value of ssorder.total_price
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.total_price
     *
     * @param totalPrice the value for ssorder.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssorder.Comment
     *
     * @return the value of ssorder.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssorder.Comment
     *
     * @param comment the value for ssorder.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}