package com.nf147.distrbution.entity;

import java.math.BigDecimal;

public class Ssroute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.route_id
     *
     * @mbg.generated
     */
    private String routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.city_id
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.province_id
     *
     * @mbg.generated
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.route_name
     *
     * @mbg.generated
     */
    private String routeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.start_province
     *
     * @mbg.generated
     */
    private String startProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.start_city
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.end_province
     *
     * @mbg.generated
     */
    private String endProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.end_city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.mid_province
     *
     * @mbg.generated
     */
    private String midProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.mid_city
     *
     * @mbg.generated
     */
    private String midCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.transport_price
     *
     * @mbg.generated
     */
    private BigDecimal transportPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ssroute.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.route_id
     *
     * @return the value of ssroute.route_id
     *
     * @mbg.generated
     */
    public String getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.route_id
     *
     * @param routeId the value for ssroute.route_id
     *
     * @mbg.generated
     */
    public void setRouteId(String routeId) {
        this.routeId = routeId == null ? null : routeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.city_id
     *
     * @return the value of ssroute.city_id
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.city_id
     *
     * @param cityId the value for ssroute.city_id
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.province_id
     *
     * @return the value of ssroute.province_id
     *
     * @mbg.generated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.province_id
     *
     * @param provinceId the value for ssroute.province_id
     *
     * @mbg.generated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.route_name
     *
     * @return the value of ssroute.route_name
     *
     * @mbg.generated
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.route_name
     *
     * @param routeName the value for ssroute.route_name
     *
     * @mbg.generated
     */
    public void setRouteName(String routeName) {
        this.routeName = routeName == null ? null : routeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.start_province
     *
     * @return the value of ssroute.start_province
     *
     * @mbg.generated
     */
    public String getStartProvince() {
        return startProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.start_province
     *
     * @param startProvince the value for ssroute.start_province
     *
     * @mbg.generated
     */
    public void setStartProvince(String startProvince) {
        this.startProvince = startProvince == null ? null : startProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.start_city
     *
     * @return the value of ssroute.start_city
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.start_city
     *
     * @param startCity the value for ssroute.start_city
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.end_province
     *
     * @return the value of ssroute.end_province
     *
     * @mbg.generated
     */
    public String getEndProvince() {
        return endProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.end_province
     *
     * @param endProvince the value for ssroute.end_province
     *
     * @mbg.generated
     */
    public void setEndProvince(String endProvince) {
        this.endProvince = endProvince == null ? null : endProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.end_city
     *
     * @return the value of ssroute.end_city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.end_city
     *
     * @param endCity the value for ssroute.end_city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.mid_province
     *
     * @return the value of ssroute.mid_province
     *
     * @mbg.generated
     */
    public String getMidProvince() {
        return midProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.mid_province
     *
     * @param midProvince the value for ssroute.mid_province
     *
     * @mbg.generated
     */
    public void setMidProvince(String midProvince) {
        this.midProvince = midProvince == null ? null : midProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.mid_city
     *
     * @return the value of ssroute.mid_city
     *
     * @mbg.generated
     */
    public String getMidCity() {
        return midCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.mid_city
     *
     * @param midCity the value for ssroute.mid_city
     *
     * @mbg.generated
     */
    public void setMidCity(String midCity) {
        this.midCity = midCity == null ? null : midCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.transport_price
     *
     * @return the value of ssroute.transport_price
     *
     * @mbg.generated
     */
    public BigDecimal getTransportPrice() {
        return transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.transport_price
     *
     * @param transportPrice the value for ssroute.transport_price
     *
     * @mbg.generated
     */
    public void setTransportPrice(BigDecimal transportPrice) {
        this.transportPrice = transportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ssroute.comment
     *
     * @return the value of ssroute.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ssroute.comment
     *
     * @param comment the value for ssroute.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}